name: KnockBackFFA
main: KnockbackFFA\KnockbackFFA
version: 2.0
api: 
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
author: zBearchenPlayz
commands:
  knockit:
    description: KnockIt Arena beitreten
  kt:
    description: KnockIt Arena beitreten
