name: KnockbackFFA
main: KnockBackFFA\KnockbackFFA
version: 2.0
api: 
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
author: McpeBooster [Fixed by zBearchenPlayz]
commands:
  knockbackffa:
    description: KnockBackFFA beitreten
  kbf:
    description: KnockBackFFA beitreten
